import type {Metadata} from "next";
import "./globals.css";
import React from "react";
import Navbar from "@/components/Navbar";
import ReactQueryProvider from "@/providers/ReactQueryProvider";

export const metadata: Metadata = {
  title: "Quick Book",
  description: "Generated by create next app",
};


export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
    <body
      className={`antialiased`}
    >
    <ReactQueryProvider>
      <Navbar/>
      {children}
    </ReactQueryProvider>
    </body>
    </html>
  );
}
