import type {Metadata} from "next";
import {Geist, Geist_Mono, Open_Sans} from "next/font/google";
import "./globals.css";
import {AuthProvider} from "@/features/auth/hooks/AuthContext";
import NavBar from "@/components/NavBar/NavBar";
import {BusinessProvider} from "@/features/business/hooks/BusinessContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
    <body
      className={` ${openSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased w-full bg-background`}
    >
    <AuthProvider>
      <BusinessProvider>
        <NavBar/>
        {children}
      </BusinessProvider>
    </AuthProvider>
    </body>
    </html>
  );
}
